### ISSUE TITLE
Memory Usage Preprocessing

### ISSUE THREAD

**Issue by yazdanbakhsh** [facebookresearch/CodeGen#27]
When running preprocessing on all the data,  it seems that the job consumes almost all the memory on the system and the swap memory. It makes the whole job very slow (after 1-2 days only 10-100 files processed). I am wondering if there is any way to put a limit on the number of files that are loaded into the memory concurrently.

I see that there is an option `job_mem` when the job is running on clusters, but not when the job is running locally.

**Comment by brozi** [comment]
I guess you are running with submitit's local executor (corresponding to --local=True). Unfortunately there is no parameter in submitit at the moment to limit the number of jobs that run concurrently (therefore limiting the number of files loaded in memory concurrently). We were using the local mode only to run the pipeline locally on small datasets but never ran it on full datasets with this mode. 
You could either run these jobs on a cluster that can be interfaced with submitit using --local=False or modify the code to replace `executor.map_array` with a for loop (or the executor with a multiprocessing.pool object) in [dataset_mode](https://github.com/facebookresearch/CodeGen/blob/main/codegen_sources/preprocessing/dataset_modes/dataset_mode.py). As you are probably not the only one who wants to run the pipeline locally and are experiencing this issue, we will push a fix for that later, ideally by adding this option in submitit. 

Note: the job_mem option sets the memory of the cluster the preprocessing jobs run on.

**Comment by yazdanbakhsh** [comment]
Thank you so much. We will try it out.

**Comment by yazdanbakhsh** [comment]
Thanks Yassas for bringing this issue up. I think what he is referring to is the following line: 

https://github.com/facebookresearch/CodeGen/blob/fb42dcb2403844672f67fc9e6e7a2726abf3b6b6/codegen_sources/preprocessing/dataset_modes/dataset_mode.py#L215

which calls `checkpoint_line`

https://github.com/facebookresearch/CodeGen/blob/fb42dcb2403844672f67fc9e6e7a2726abf3b6b6/codegen_sources/preprocessing/dataset_modes/dataset_mode.py#L302

**Comment by yazdanbakhsh** [comment]
I tried to create a pool request, but it seems it involves multiple approvals which may take time. I'd suggest to also add an option to limit the degree of parallelism in the `checkpoint_line` or other places where `Pool` is used instead of relying on `cpu_count`.

**Comment by brozi** [comment]
Thanks yazdanbakhsh for creating a PR. I don't think there was any new commit in it so you probably had some issues pushing your code to this branch. You could try pushing your commits to a new branch and submitting a PR. 
You would be able to merge it the code passes the automatic tests and if a code owner approves the PR (for instance if I approve it).
