### ISSUE TITLE
How two checkpoints are selected in TransCoder?

### ISSUE THREAD

**Issue by wasiahmad** [facebookresearch/CodeGen#31]
For the TransCoder model, two separate checkpoints are provided for the following language directions.

- TransCoder_model_1 for C++ -> Java, Java -> C++ and Java -> Python
- TransCoder_model_2 for C++ -> Python, Python -> C++ and Python -> Java

Did you train TransCoder individually for the above two different directions setting? Or, the checkpoint is selected based on validation performances for those directions.

**Comment by brozi** [comment]
Hi. The checkpoints were selected based on the validation performances on a single run. We tried to select two checkpoints with close to the best validation performance for several pairs to avoid having to one model per direction.
