### ISSUE TITLE
Preprocess complete but running into issues when training

### ISSUE THREAD

**Issue by lhendre** [facebookresearch/CodeGen#5]
Hello,
I ran the preprocess step and it appeared to complete successfully; however, after I run the following command to train

python codegen_sources/model/train.py --exp_name transcoder --dump_path './model1' --data_path '/content/CodeGen/data/test_dataset/XLM-syml' --split_data_accross_gpu local --bt_steps 'python_sa-java_sa-python_sa,java_sa-python_sa-java_sa'  --ae_steps 'python_sa,java_sa'  --lambda_ae '0:1,30000:0.1,100000:0'  \--word_shuffle 3  --word_dropout '0.1' --word_blank '0.3'  --encoder_only False --n_layers 0  --n_layers_encoder 12  --n_layers_decoder 6 --emb_dim 768  --n_heads 12  --lgs 'java_sa-python_sa'  --max_vocab 64000 --gelu_activation true --roberta_mode true   --lgs_mapping 'java_sa:java_obfuscated,python_sa:python_obfuscated'  --amp 2  --fp16 true  --tokens_per_batch 3000  --group_by_size true --max_batch_size 128 --epoch_size 50000  --max_epoch 10000000  --split_data_accross_gpu global --optimizer 'adam_inverse_sqrt,warmup_updates=10000,lr=0.0001,weight_decay=0.01' --eval_bleu true --eval_computation true --generate_hypothesis true --save_periodic 1 --validation_metrics 'valid_python_sa-java_sa_mt_comp_acc'  

I ran into the following error.

INFO - 08/04/21 18:32:16 - 0:00:00 - ============ Monolingual data (python_sa)
INFO - 08/04/21 18:32:16 - 0:00:00 - Loading data from /content/CodeGen/data/test_dataset/XLM-syml/train.python_sa.0.pth ...
INFO - 08/04/21 18:32:16 - 0:00:00 - 37514 words (50775 unique) in 250 sentences. 0 unknown words (0 unique) covering 0.00% of the data.
INFO - 08/04/21 18:32:16 - 0:00:00 - Selecting 64000 most frequent words ...
INFO - 08/04/21 18:32:16 - 0:00:00 - Maximum vocabulary size: 64000. Dictionary size: 50775 -> 50775 (removed 0 words).
INFO - 08/04/21 18:32:16 - 0:00:00 - Now 0 unknown words covering 0.00% of the data.
INFO - 08/04/21 18:32:17 - 0:00:01 - Removed 0 empty sentences.
INFO - 08/04/21 18:32:17 - 0:00:01 - Removed 0 empty sentences.
INFO - 08/04/21 18:32:17 - 0:00:01 - Removed 111 too long sentences.

INFO - 08/04/21 18:32:17 - 0:00:01 - Loading data from /content/CodeGen/data/test_dataset/XLM-syml/valid.python_sa.pth ...
INFO - 08/04/21 18:32:17 - 0:00:01 - 3088 words (50775 unique) in 25 sentences. 0 unknown words (0 unique) covering 0.00% of the data.
INFO - 08/04/21 18:32:17 - 0:00:01 - Selecting 64000 most frequent words ...
INFO - 08/04/21 18:32:17 - 0:00:01 - Maximum vocabulary size: 64000. Dictionary size: 50775 -> 50775 (removed 0 words).
INFO - 08/04/21 18:32:17 - 0:00:01 - Now 0 unknown words covering 0.00% of the data.
INFO - 08/04/21 18:32:17 - 0:00:01 - Removed 0 empty sentences.

INFO - 08/04/21 18:32:17 - 0:00:01 - Loading data from /content/CodeGen/data/test_dataset/XLM-syml/test.python_sa.pth ...
INFO - 08/04/21 18:32:17 - 0:00:01 - 8581 words (50775 unique) in 43 sentences. 0 unknown words (0 unique) covering 0.00% of the data.
INFO - 08/04/21 18:32:17 - 0:00:01 - Selecting 64000 most frequent words ...
INFO - 08/04/21 18:32:17 - 0:00:01 - Maximum vocabulary size: 64000. Dictionary size: 50775 -> 50775 (removed 0 words).
INFO - 08/04/21 18:32:17 - 0:00:01 - Now 0 unknown words covering 0.00% of the data.
INFO - 08/04/21 18:32:17 - 0:00:01 - Removed 0 empty sentences.

INFO - 08/04/21 18:32:17 - 0:00:01 - ============ Parallel data (java_sa-python_sa)
INFO - 08/04/21 18:32:17 - 0:00:01 - Loading data from /content/CodeGen/data/test_dataset/XLM-syml/valid.java_sa-python_sa.java_sa.pth ...
INFO - 08/04/21 18:32:17 - 0:00:01 - 66397 words (64461 unique) in 470 sentences. 0 unknown words (0 unique) covering 0.00% of the data.
INFO - 08/04/21 18:32:17 - 0:00:01 - Selecting 64000 most frequent words ...
INFO - 08/04/21 18:32:17 - 0:00:01 - Maximum vocabulary size: 64000. Dictionary size: 64461 -> 64000 (removed 461 words).
INFO - 08/04/21 18:32:17 - 0:00:01 - Now 0 unknown words covering 0.00% of the data.
INFO - 08/04/21 18:32:17 - 0:00:01 - Loading data from /content/CodeGen/data/test_dataset/XLM-syml/valid.java_sa-python_sa.python_sa.pth ...
INFO - 08/04/21 18:32:17 - 0:00:01 - 63023 words (64461 unique) in 470 sentences. 0 unknown words (0 unique) covering 0.00% of the data.
INFO - 08/04/21 18:32:17 - 0:00:01 - Selecting 64000 most frequent words ...
INFO - 08/04/21 18:32:17 - 0:00:01 - Maximum vocabulary size: 64000. Dictionary size: 64461 -> 64000 (removed 461 words).
INFO - 08/04/21 18:32:17 - 0:00:01 - Now 0 unknown words covering 0.00% of the data.
Traceback (most recent call last):
  File "codegen_sources/model/train.py", line 701, in <module>
    main(params)
  File "codegen_sources/model/train.py", line 556, in main
    data = load_data(params)
  File "/content/CodeGen/codegen_sources/model/src/data/loader.py", line 582, in load_data
    load_para_data(params, data)
  File "/content/CodeGen/codegen_sources/model/src/data/loader.py", line 278, in load_para_data
    set_dico_parameters(params, data, src_data["dico"])
  File "/content/CodeGen/codegen_sources/model/src/data/loader.py", line 117, in set_dico_parameters
    assert data["dico"] == dico
AssertionError

I was having this origional issue on the transcoder as well(didnt end up solving it, saw this came out and switched to try CodeGen).  It seems to be related to the parallel data; however, I pulled that from your source so Im a little bit perplexedand not sure where to look

**Comment by malachaux** [comment]
If you have run the the prepocessing pipeline with our BPE codes and vocab, you should not have this issue. 
If you have learn your own bpe codes and vocab, you should preprocess the parallel test data we gave you:
- you should take the tokenized data .tok
- apply your own BPE codes - create a fast_bpe_dataset_mode with your bpe codes files and use this method https://github.com/facebookresearch/CodeGen/blob/master/codegen_sources/preprocessing/bpe_modes/fast_bpe_mode.py#L81
- binarize the .bpe files (.pth)  with your own vocabulary -> use https://github.com/facebookresearch/CodeGen/blob/master/codegen_sources/preprocessing/utils.py#L169

Anyway, if you only work with Python, Java or CPP programming languages, so I do not see a clear reason why you should not use our BPE codes and vocab.

**Comment by lhendre** [comment]
So I went back and tried using the pre provided  BPE codes and vocab and Im still running into issues.  Im getting a file Not Founder error "No such file or direwctory: '.../ypotheses/ids.cpp_sa-java_sa.valid.txt'".  At this point to im doing everything as suggested so Im not sure what the issue is
