### ISSUE TITLE
How to extract functions?

### ISSUE THREAD

**Issue by skye95git** [facebookresearch/CodeGen#6]
I have downloaded the raw source code on my machine, for example, `python.000000000000.json.gz`.
But when I run preprocessing pipeline, there is an error:
`AssertionError: failed to learn bpe on /data2/linjiayi/CodeGen-master/data/python.sa-cl.tok.shuf.50gb, command: /home/linjiayi/CodeGen-master/codegen_sources/model/tools/fastBPE/fast learnbpe 50000 /data2/linjiayi/CodeGen-master/data/python.sa-cl.tok.shuf.50gb > /data2/linjiayi/CodeGen-master/data/python.sa-cl.codes`

After I changed the filename to `python.000.json.gz`, it run successfully. Actually, I only want to extract functions from the raw source code. So, I have a few questions:

1. Can data downloaded from BigQuery only be named in python.*[0-4][0-9][0-9].json.gz format? 

2. When I import data from BigQuery Table into Google Storage using wildcards, the file named python.000000000000.json.gz. How to save a file name with only three zeros? Did you download the file and modify it?

3. After I run preprocessing pipeline, only one `python.000.json.gz` generates a lot of files. 
<img width="803" alt="捕获1" src="https://user-images.githubusercontent.com/41561936/128341411-d31b47b0-f71b-4fb3-aee7-a620ed9bbbbf.PNG">
The `.sa.tok` files is `standalone functions.` The `.cl.tok` files is `class functions`. What's in the other files?

4. Whether the Preprocessing Pipeline can extract description for each function? Which file to save the description in?

5. The format of the extracted function is
`robertglen/flask | def test_explicit_instance_paths ( modules_tmpdir ) : NEW_LINE INDENT with pytest . raises ( ValueError ) as excinfo : NEW_LINE INDENT flask . Flask ( __name__ , instance_path = ' instance ' ) NEW_LINE DEDENT assert ' must ▁ be ▁ absolute ' in str ( excinfo . value ) NEW_LINE app = flask . Flask ( __name__ , instance_path = str ( modules_tmpdir ) ) NEW_LINE assert app . instance_path == str ( modules_tmpdir ) NEW_LINE DEDENT
`
There are NEW_LINE INDENT, NEW_LINE DEDENT and NEW_LINE in the cdoes. Whether they affect the parsing of the code?

**Comment by skye95git** [comment]
Whether CodeGen's preprocessing steps can extract comments? I find there is a parameter `--keep_comments` in TransCoder. But CodeGen doesn't have.

**Comment by malachaux** [comment]
1/2 - This format python.*[0-4][0-9][0-9].json.gz includes python.000000000000.json.gz because of the `*`, so this works with this format as well. If this would be the error, then you will have had an error at the very first step "no json files found in folder". The error you have is very often due to the facts you ask to learn 50k codes on only a signle small python json. You should consider learning fewer codes and learning on more data.

3 - The others file are intermediate files necessary to run the pipeline, what you want to keep is only the .pth and their symlinks.

4- no feature in the pipeline to have description

5- we only keep the keep-comments=True by default as it is what we use in our models, but you can easily add a param to do so and set this params to False, as we still have keep-comments params in all tokenization/function extraction functions.

**Comment by skye95git** [comment]
> 1/2 - This format python.*[0-4][0-9][0-9].json.gz includes python.000000000000.json.gz because of the `*`, so this works with this format as well. If this would be the error, then you will have had an error at the very first step "no json files found in folder". The error you have is very often due to the facts you ask to learn 50k codes on only a signle small python json. You should consider learning fewer codes and learning on more data.
> 
> 3 - The others file are intermediate files necessary to run the pipeline, what you want to keep is only the .pth and their symlinks.
> 
> 4- no feature in the pipeline to have description
> 
> 5- we only keep the keep-comments=True by default as it is what we use in our models, but you can easily add a param to do so and set this params to False, as we still have keep-comments params in all tokenization/function extraction functions.

Do you keep the keep-comments=True by default? So I don't need to set keep-comments=True in CodeGen, right? 
But I run the preprocess code and get the functions without comments:
<img width="501" alt="捕获5" src="https://user-images.githubusercontent.com/41561936/128803939-0ca349d0-2ebf-4e57-8a3f-8f8f82743f00.PNG">


When keep-comments is set to True, doesn't it mean keeping comments in the code? Why does the extracted function have no comments?

**Comment by skye95git** [comment]
> 1/2 - This format python.*[0-4][0-9][0-9].json.gz includes python.000000000000.json.gz because of the `*`, so this works with this format as well. If this would be the error, then you will have had an error at the very first step "no json files found in folder". The error you have is very often due to the facts you ask to learn 50k codes on only a signle small python json. You should consider learning fewer codes and learning on more data.
> 
> 3 - The others file are intermediate files necessary to run the pipeline, what you want to keep is only the .pth and their symlinks.
> 
> 4- no feature in the pipeline to have description
> 
> 5- we only keep the keep-comments=True by default as it is what we use in our models, but you can easily add a param to do so and set this params to False, as we still have keep-comments params in all tokenization/function extraction functions.

The `description` in the fourth question means `comment`. Now I can extract functions. But the comments can't be extracted. How can I extract functions with comments?
