### ISSUE TITLE
Training transcoder Generates same token at the beginning of training

### ISSUE THREAD

**Issue by CosmoLuminous** [facebookresearch/CodeGen#78]
When I initiate the transcoder training, for the BT step it shows `generated source sent:` with the same repeated token `=`. Just wanted to check if this is an expected behaviour or am I wrong somewhere? Also, if you could share a dummy `train.log` file of an already trained model here for my reference it would be helpful. 

INFO - 06/02/22 02:18:54 - 0:00:31 - Generated source sent: `</s> = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =  </s>`

INFO - 06/02/22 02:18:54 - 0:00:31 - Target (x1) sent: `</s> class var4_class { int var5 = 5 ; double var6 = 4.62 ; } public class java_4_20_23 { public static void main ( String [ ] args ) { int var0 = 3 ; double var1 = 4.57 ; String var2 = " vahjj " ; double var3 = 1.37 ; var4_class var4 = new var4_class ( ) ; int var7 = 1 ; int var8 = 4 ; var8 = var7 * var7 ; var1 = var3 ; System . out . println ( " var0 = " + var0 ) ; System . out . println ( " var1 = " + var1 ) ; System . out . println ( " var2 = " + var2 ) ; System . out . println ( " var3 = " + var3 ) ; System . out . println ( " var5 = " + var4 . var5 ) ; System . out . println ( " var6 = " + var4 . var6 ) ; System . out . println ( " var7 = " + var7 ) ; System . out . println ( " var8 = " + var8 ) ; } } </s>`

**Comment by brozi** [comment]
Hi, 
Yes it's normal at the beginning of training. The model hasn't been trained to generate correct sentences yet and tends to generate bad sentences. After more updates, it should start generating correct-looking programs and improve afterwards.
