### ISSUE TITLE
Attempt to download MLM pre-trained model - access denied

### ISSUE THREAD

**Issue by dowenk** [facebookresearch/CodeGen#8]
wget https://dl.fbaipublicfiles.com/transcoder/pre_trained_models/mlm.pth

--2021-08-20 11:35:20--  https://dl.fbaipublicfiles.com/transcoder/pre_trained_models/mlm.pth
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 104.22.75.142, 104.22.74.142, 172.67.9.4, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|104.22.75.142|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-08-20 11:35:20 ERROR 403: Forbidden.

**Comment by brozi** [comment]
Sorry we forgot to update this link in the ReadME. This one should work:
```
wget https://dl.fbaipublicfiles.com/transcoder/pre_trained_models/mlm_roberta_size.pth
```

**Comment by brozi** [comment]
We updated the ReadME with the correct link.
