### ISSUE TITLE
Go and Rust models

### ISSUE THREAD

**Issue by hfeniser** [facebookresearch/CodeGen#99]
Are you thinking to share the models for your latest models? I am particularly interested in Go-Rust and Rust-Go models.

**Comment by MarcSzafraniec** [comment]
I believe you can find them there :) https://github.com/facebookresearch/CodeGen/blob/main/docs/TransCoder-IR.md

**Comment by hfeniser** [comment]
Ah, thank you for the pointer :) I think it would be cool to add a link to those models in the main README.
